export {default as AnimatedBackground } from './component/AnimatedBackground'
export { VideoProvider } from './context/Provider'
export { videoReducer } from './context/Reducer'
export { default as VideoContext } from './context/Context'
export { type VideoBGContextType } from './types'
export { type VideoAction, type VideoState, type VideoKeys } from './types'