// src/utils/pwa-utils.ts
import { Workbox } from 'workbox-window';

export const clearVideoCache = async () => {
  if ('serviceWorker' in navigator) {
    const registration = await navigator.serviceWorker.ready;
    registration.active?.postMessage({ type: 'CLEAR_VIDEO_CACHE' });
  }
};

export const registerSW = () => {
  if ('serviceWorker' in navigator) {
    // In development, Vite serves the service worker at a different path
    // In production, it will be at /sw.js
    const swUrl = import.meta.env.DEV ? '/sw.js' : '/sw.js';
    
    if (import.meta.env.DEV) {
      // In development mode, the service worker is generated by VitePWA
      // Check if the service worker file exists before registering
      if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register(swUrl)
          .then((registration) => {
            console.log('SW registered:', registration);
          })
          .catch((error) => {
            console.error('SW registration failed: ', error);
          });
      }
    } else {
      // In production, use Workbox for more advanced features
      const wb = new Workbox(swUrl);
      wb.register().then((registration) => {
        console.log('SW registrado:', registration);
      }).catch((error) => {
        console.error('SW registration failed: ', error);
      });
      return wb;
    }
  }
  return null;
};